# Generated by Django 4.0.1 on 2022-01-14 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 15, 16, 18, 735233, tzinfo=utc), verbose_name='date closed'),
        ),
    ]
