# Generated by Django 4.0.1 on 2022-01-15 04:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_question_max_choices_alter_question_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='made_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 4, 55, 2, 448097, tzinfo=utc), verbose_name='date closed'),
        ),
    ]
