# Generated by Django 4.0.1 on 2022-01-15 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_made_by_alter_question_closed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='made_by',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 4, 56, 53, 696130, tzinfo=utc), verbose_name='date closed'),
        ),
    ]
